import Footer from './components/Footer'
import Navbar from './components/Navbar'
import Navigation from './components/Navigation'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Shane Rose || Portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body>
        <Navbar />
        <Navigation />
        {children}
        <Footer />
      </body>
    </html>
  )
}
